# Generated by Django 3.2.7 on 2021-10-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jwt',
        ),
    ]
