# Generated by Django 3.2.7 on 2022-01-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_alter_jwt_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jwt',
        ),
    ]
