# Generated by Django 3.2.6 on 2021-09-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20210906_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelx',
            old_name='test_model',
            new_name='test_content',
        ),
    ]
