# Generated by Django 3.2.7 on 2021-10-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_modely'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modely',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'ModelY'},
        ),
    ]
