# Generated by Django 3.2.7 on 2021-10-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_modely_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modely',
            name='test_content',
        ),
        migrations.DeleteModel(
            name='ModelX',
        ),
        migrations.DeleteModel(
            name='ModelY',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
