# Generated by Django 3.2.7 on 2022-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211208_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
