# Generated by Django 3.2.7 on 2022-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
