# Generated by Django 3.2.7 on 2022-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_mobile_customuser_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
