# Generated by Django 3.2.7 on 2022-01-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
