# Generated by Django 3.2.7 on 2022-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
