# Generated by Django 3.2.7 on 2022-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
