# Generated by Django 3.2.7 on 2022-01-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_customuser_isverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isVerified',
        ),
    ]
