# Generated by Django 3.2.7 on 2022-01-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_controller', '0002_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventfeature',
            name='eventmain',
        ),
        migrations.RemoveField(
            model_name='eventmain',
            name='address_info',
        ),
        migrations.RemoveField(
            model_name='eventmain',
            name='author',
        ),
        migrations.DeleteModel(
            name='EventAttendant',
        ),
        migrations.DeleteModel(
            name='EventFeature',
        ),
        migrations.DeleteModel(
            name='EventMain',
        ),
    ]
